# Eliminating loops


In [49]:
#import 
from itertools import combinations
import numpy as np


In [50]:

# List of HP, Attack, Defense, Speed
poke_stats = [
[90, 92, 75, 60],
[25, 20, 15, 90],
[65, 130, 60, 75],

]
poke_stats

[[90, 92, 75, 60], [25, 20, 15, 90], [65, 130, 60, 75]]

In [51]:
# For loop approach
totals = []
for row in poke_stats:
    totals.append(sum(row))
totals


[317, 150, 330]

In [52]:
# List comprehension
totals_comp =[sum(row) for row in poke_stats]
totals_comp

[317, 150, 330]

In [53]:
# Built-in map() function
totals_map =[*map(sum , poke_stats)]
totals_map

[317, 150, 330]

### Eliminating loops with built-in modules


In [54]:
poke_types = ['Bug','Fire','Ghost','Grass','Water']
poke_types

['Bug', 'Fire', 'Ghost', 'Grass', 'Water']

In [55]:
combos = []
for x in poke_types:
    for y in poke_types:
        if x == y:
            continue
        if ((x,y) not in combos) & ((y,x) not in combos):
            combos.append((x,y))
combos

[('Bug', 'Fire'),
 ('Bug', 'Ghost'),
 ('Bug', 'Grass'),
 ('Bug', 'Water'),
 ('Fire', 'Ghost'),
 ('Fire', 'Grass'),
 ('Fire', 'Water'),
 ('Ghost', 'Grass'),
 ('Ghost', 'Water'),
 ('Grass', 'Water')]

In [56]:
# Built-in module approach
combos2=[*combinations(poke_types , 2)]
combos2

[('Bug', 'Fire'),
 ('Bug', 'Ghost'),
 ('Bug', 'Grass'),
 ('Bug', 'Water'),
 ('Fire', 'Ghost'),
 ('Fire', 'Grass'),
 ('Fire', 'Water'),
 ('Ghost', 'Grass'),
 ('Ghost', 'Water'),
 ('Grass', 'Water')]

In [57]:
#ex
n1=list(range(4))

In [58]:
nco=[*combinations(n1,2)]
nco

[(0, 1), (0, 2), (0, 3), (1, 2), (1, 3), (2, 3)]

In [59]:
#

### Eliminate loops with NumPy


In [62]:
# Array of HP, Attack, Defense, Speed

poke_stats = np.array([
[90, 92, 75, 60],
[25, 20, 15, 90],
[65, 130, 60, 75],
])
poke_stats

array([[ 90,  92,  75,  60],
       [ 25,  20,  15,  90],
       [ 65, 130,  60,  75]])

In [64]:
avgs = []
for row in poke_stats:
    avg = np.mean(row)
    avgs.append(avg)
print(avgs)

[79.25, 37.5, 82.5]


In [65]:
avgs_np = poke_stats.mean(axis=1)
avgs_np

array([79.25, 37.5 , 82.5 ])

In [66]:
#ex
num=np.array([ [70,80], 
              [50,70],
              [30,60]
             ])

In [67]:
num.mean(axis=1)

array([75., 60., 45.])

In [68]:
num.mean(axis=0)

array([50., 70.])

## Exercise


### Gathering Pokémon without a loop


In [ ]:
## Gathering Pokémon without a loop

# Collect Pokémon that belong to generation 1 or generation 2
gen1_gen2_pokemon = [name for name,gen in zip(poke_names, poke_gens) if gen <3]

# Create a map object that stores the name lengths
name_lengths_map = map(len, gen1_gen2_pokemon)

# Combine gen1_gen2_pokemon and name_lengths_map into a list
gen1_gen2_name_lengths = [*zip(gen1_gen2_pokemon, name_lengths_map)]

print(gen1_gen2_name_lengths_loop[:5])
print(gen1_gen2_name_lengths[:5])


## List comprehension 
[(name, len(name)) for name,gen in zip(poke_names, poke_gens) if gen < 3]

### Pokémon totals and averages without a loop


In [ ]:
# Create a total stats array
total_stats_np = stats.sum(axis=1)

# Create an average stats array
avg_stats_np = stats.mean(axis=1)

# Combine names, total_stats_np, and avg_stats_np into a list
poke_list_np = [*zip(names, total_stats_np, avg_stats_np)]

print(poke_list_np == poke_list, '\n')
print(poke_list_np[:3])
print(poke_list[:3], '\n')
top_3 = sorted(poke_list_np, key=lambda x: x[1], reverse=True)[:3]
print('3 strongest Pokémon:\n{}'.format(top_3))