# The power of NumPy arrays


In [1]:
#import 
import numpy as np

In [2]:
#Alternative to Python lists
nums_list = list(range(5))
nums_list

[0, 1, 2, 3, 4]

In [3]:
nums_np = np.array(range(5))
nums_np

array([0, 1, 2, 3, 4])

In [4]:
# NumPy array homogeneity
nums_np_ints = np.array([1, 2, 3])
nums_np_ints

array([1, 2, 3])

In [5]:
nums_np_ints.dtype

dtype('int32')

In [6]:
nums_np_floats = np.array([1, 2.5, 3])
nums_np_floats

array([1. , 2.5, 3. ])

In [7]:
nums_np_floats.dtype

dtype('float64')

### NumPy array broadcasting


In [9]:
# Python lists don't support broadcasting
nums = [-2,-1, 0, 1, 2]
nums ** 2 # eror

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

#### List approach


In [10]:
# For loop (inefficient option)
sqrd_nums = []
for num in nums:
    sqrd_nums.append(num ** 2)
print(sqrd_nums)


[4, 1, 0, 1, 4]


In [11]:
# List comprehension (better option but not best)
sqrd_nums = [num ** 2 for num in nums]
print(sqrd_nums)


[4, 1, 0, 1, 4]


##### NumPy array broadcasting for the win!


In [12]:
nums_np = np.array([-2,-1, 0, 1, 2])

nums_np ** 2

array([4, 1, 0, 1, 4], dtype=int32)

##### Basic 1-D indexing (lists)


In [13]:
nums = [-2,-1, 0, 1, 2]
nums[2]

0

In [14]:
nums[-1]


2

In [15]:
nums[1:4]


[-1, 0, 1]

##### Basic 1-D indexing (arrays)


In [16]:
nums_np = np.array(nums)
nums_np[2]


0

In [17]:
nums_np[-1]


2

In [18]:
nums_np[1:4]

array([-1,  0,  1])

In [19]:
# 2-D list
nums2 = [ [1, 2, 3],
        [4, 5, 6] ]

##### Basic 2-D indexing (lists)


In [20]:
nums2[0][1]


2

In [21]:
[row[0] for row in nums2]

[1, 4]

##### Basic 2-D indexing (arrays)


In [22]:
# 2-D array
nums2_np = np.array(nums2)


In [23]:
nums2_np[0,1]


2

In [24]:
nums2_np[:,0]

array([1, 4])

### NumPy array boolean indexing


In [25]:
nums = [-2,-1, 0, 1, 2]
nums_np = np.array(nums)
nums_np

array([-2, -1,  0,  1,  2])

##### Boolean indexing


In [27]:
nums_np > 0

array([False, False, False,  True,  True])

In [28]:
nums_np[nums_np > 0]


array([1, 2])

## Exercise


### Practice with NumPy arrays


In [31]:
nums= np.array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

# Print second row of nums
print(nums[1,:])

# Print all elements of nums that are greater than six
print(nums[nums > 6])

# Double every element of nums
nums_dbl = nums * 2
print(nums_dbl)

# Replace the third column of nums
nums[:,2] = nums[:,2] + 1
print(nums)

[ 6  7  8  9 10]
[ 7  8  9 10]
[[ 2  4  6  8 10]
 [12 14 16 18 20]]
[[ 1  2  4  4  5]
 [ 6  7  9  9 10]]


### Bringing it all together: Festivus!


In [33]:
# Create a list of arrival times
arrival_times = [*range(10, 60, 10)]

print(arrival_times)

[10, 20, 30, 40, 50]


In [34]:
# Create a list of arrival times
arrival_times = [*range(10,60,10)]

# Convert arrival_times to an array and update the times
arrival_times_np = np.array(arrival_times)
new_times = arrival_times_np - 3

print(new_times)

[ 7 17 27 37 47]


In [36]:
names= ['Jerry', 'Kramer', 'Elaine', 'George', 'Newman']


# Create a list of arrival times
arrival_times = [*range(10,60,10)]

# Convert arrival_times to an array and update the times
arrival_times_np = np.array(arrival_times)
new_times = arrival_times_np - 3

# Use list comprehension and enumerate to pair guests to new times
guest_arrivals = [(names[i],time) for i,time in enumerate(new_times)]

print(guest_arrivals)

[('Jerry', 7), ('Kramer', 17), ('Elaine', 27), ('George', 37), ('Newman', 47)]


In [37]:
# Create a list of arrival times
arrival_times = [*range(10,60,10)]

# Convert arrival_times to an array and update the times
arrival_times_np = np.array(arrival_times)
new_times = arrival_times_np - 3

# Use list comprehension and enumerate to pair guests to new times
guest_arrivals = [(names[i],time) for i,time in enumerate(new_times)]

# Map the welcome_guest function to each (guest,time) pair
welcome_map = map(welcome_guest, guest_arrivals)

guest_welcomes = [*welcome_map]
print(*guest_welcomes, sep='\n')

NameError: name 'welcome_guest' is not defined